# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
development:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] %>
  inline: true
  timeout: 1

production:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] %>
  inline: true
  timeout: 1
  host: pub-redis-13023.us-east-1-2.5.ec2.garantiadata.com
  port: 13023

test:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] %>
  inline: true
  timeout: 1
